### ISSUE TITLE
can't install on debian 10 ( buster ) docker

### ISSUE THREAD

**Issue by lycoch** [deletescape/goop#3] opened 2020-11-06 10:19 UTC
hello
i'm not a go expert, please be warn

i just run a brand new debian 10 via docker:

$ apt update; apt install golang
$ go get -u github.com/deletescape/goop

the directory is full of things: /root/go/src/github.com/deletescape/goop
but how are we supposed to lunch the software ?
"goop" is not reconized as a command

so i tried:
$ go run /root/go/src/github.com/deletescape/goop/main.go http://test.com
same with
$ go run /root/go/src/github.com/deletescape/goop/cmd/goop.go http://test.com

it fails with:
/root/go/src/github.com/go-git/go-git/storage/filesystem/dotgit/dotgit.go:17:2: code in directory /root/go/src/github.com/go-git/go-billy/osfs expects import "github.com/go-git/go-billy/v5/osfs"

thank you

**Comment by deletescape** [comment] 2020-11-06 16:08
if goop is not recognized as a command at all then the go bin path is probably not added to path properly yet. And the error it gets when launching seems to be a duplicate of #2

**Comment by deletescape** [comment] 2020-11-12 19:46
see #2

**Closed by deletescape** 2020-11-12 19:46 UTC
